// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-l1LvGAfqk2T9cL6Jg_JS4pKymWfoY6M',
    appId: '1:839239962055:web:56f01d10c71f3e15561de2',
    messagingSenderId: '839239962055',
    projectId: 'blackcoffer-a7cf9',
    authDomain: 'blackcoffer-a7cf9.firebaseapp.com',
    storageBucket: 'blackcoffer-a7cf9.appspot.com',
    measurementId: 'G-0C5VS3GZWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9lKUKMPUKussQJhMcYROzol2UNS3zYq0',
    appId: '1:839239962055:android:38db928f8983746b561de2',
    messagingSenderId: '839239962055',
    projectId: 'blackcoffer-a7cf9',
    storageBucket: 'blackcoffer-a7cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJaxYfTmPwrTUK_dUGOXiFBqXtgMaXos',
    appId: '1:839239962055:ios:6c4354913b2673cd561de2',
    messagingSenderId: '839239962055',
    projectId: 'blackcoffer-a7cf9',
    storageBucket: 'blackcoffer-a7cf9.appspot.com',
    androidClientId: '839239962055-6scauim8o6rt10so1t45nmp5hl06l8la.apps.googleusercontent.com',
    iosClientId: '839239962055-k88e694s2k9sdc7284le10frkh4b79lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackcoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJaxYfTmPwrTUK_dUGOXiFBqXtgMaXos',
    appId: '1:839239962055:ios:6c4354913b2673cd561de2',
    messagingSenderId: '839239962055',
    projectId: 'blackcoffer-a7cf9',
    storageBucket: 'blackcoffer-a7cf9.appspot.com',
    androidClientId: '839239962055-6scauim8o6rt10so1t45nmp5hl06l8la.apps.googleusercontent.com',
    iosClientId: '839239962055-k88e694s2k9sdc7284le10frkh4b79lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.blackcoffer',
  );
}
